/*
  This code is mostly generated by Supevmaven
*/

#include <stdio.h>

#define HEADER "/* \n\
    Copyright Kaskobi 2014-2024 ©\n\
    All Rights Reserved\n\
    Original: Novation RGB Launchpad (Optimised for realism)\n\
    \n\
    \n\
    THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT\n\
*/  \n\
    \n\
#include QMK_KEYBOARD_H\n\
    \n\
#pragma once\n\
    \n\
/* \n\
   RGB palette\n\
   Each volue was multiplied by 4, cause there's only 0-63 in LaunchPad\n\
*/ \n\
const uint8_t PROGMEM rgb_palette[128][3] = {\n\
"
#define SOURCE "Novation+RGB+Palette+(Optimised)"

int main(int argc, char **argv) {
    FILE *pfp = fopen("rgb_palette.h", "w");
    if (!pfp) {
        perror("error fopen rgb_palette.h");
        return 1;
    }
    FILE *sfp = fopen(SOURCE, "r");
    if (!sfp) {
        perror("error fopen " SOURCE);
        return 1;
    }

    fputs(HEADER, pfp);

    int r, g, b;
    for (int i = 0; i < 128; i++) {
        fscanf(sfp, "%d, %d %d %d;", &i, &r, &g, &b);
        fprintf(pfp, "    { 0x%02X, 0x%02X, 0x%02X }, // %d\n", r * 4, g * 4, b * 4, i);
    }
    fputs("};\n", pfp);

    fclose(pfp);
    fclose(sfp);
    return 0;
}
